export default {
    TAB_SELECT: 'TAB_SELECT',

    DATASET_REQUESTED: 'DATASET_REQUESTED',
    DATASET_PENDING: 'DATASET_PENDING',
    DATASET_RECEIVED: 'DATASET_RECEIVED',

    DATASET_TOGGLE_POPULATION_VIEW: 'DATASET_TOGGLE_POPULATION_VIEW',
    DATASET_SET_VIEW_MODE: 'DATASET_SET_VIEW_MODE',
    DATASET_SELECT_SAMPLE: 'DATASET_SELECT_SAMPLE',
    DATASET_SELECT_SAMPLES: 'DATASET_SELECT_SAMPLES',
    DATASET_CHANGE_SEARCH_STRING: 'DATASET_CHANGE_SEARCH_STRING',

    MAP_UPDATE_STATE: 'MAP_UPDATE_STATE',
};
